// Barrel re-export for CCR-4 per-domain schema split.
export * from './actor.js';
export * from './item.js';
export * from './compendium.js';
export * from './scene.js';
export * from './combat.js';
export * from './conditions.js';
export * from './meta.js';
export * from './create-custom/index.js';
export * from './trade-item.js';
export * from './modify-item-qualities.js';
export * from './item-target.js';
export * from './add-active-effect.js';
export * from './update-active-effect.js';
export * from './delete-active-effect.js';
export * from './get-active-effect-by-name.js';
export * from './ownership.js';
export * from './targets.js';
export * from './outputs.js';
