// Phase 11 (R11.3): centralized error-token registry.
//
// 83 tokens: 79 `*_NOT_PERSISTED` post-verify tokens (DP-16) + 4 cross-package
// module-guard tokens. Previously scattered as bare string literals across ~90
// files in both packages.
//
// ─────────────────────────────────────────────────────────────────────────────
// HARD CONSTRAINT — token string VALUES are byte-identical to the prior literals
// (value === key for every entry). This is NOT cosmetic: the contract is the
// VALUE, not the key. Two live consumers depend on the literal value:
//   1. The 23 mcp-server module tool files that do `msg.includes('MODULE_NOT_ACTIVE')`
//      (and the 3 sibling guard tokens) to detect module-inactive responses.
//   2. foundry-module/src/transaction-manager.ts — a `/NOT_PERSISTED|VERIFY_FAILED/`
//      regex test on the error message. Every `*_NOT_PERSISTED` value preserves the
//      `_NOT_PERSISTED` suffix so that regex still matches.
// Any value change is an HC8 contract break. Migrating a literal to `ErrorTokens.X`
// is a pure syntax change — the emitted string is unchanged.
// ─────────────────────────────────────────────────────────────────────────────
//
// House style: `as const` object (mirrors constants.ts SOCKET_EVENTS/ERROR_MESSAGES),
// NOT a TS enum (enums emit runtime code + hurt tree-shaking).

export const ErrorTokens = {
  // ── Module-guard tokens (string-matched cross-package via .includes()) ──
  MODULE_NOT_ACTIVE: 'MODULE_NOT_ACTIVE',
  MODULE_DEPENDENCY_NOT_ACTIVE: 'MODULE_DEPENDENCY_NOT_ACTIVE',
  COMPANION_NOT_ACTIVE: 'COMPANION_NOT_ACTIVE',
  SOCKETLIB_NOT_ACTIVE: 'SOCKETLIB_NOT_ACTIVE',

  // ── Input-validation rejection tokens (Phase 12 R12.3) ──
  // Pre-write INPUT rejection (the field never reaches actor.update), NOT a post-write verify failure —
  // deliberately omits the `_NOT_PERSISTED` suffix so transaction-manager's /NOT_PERSISTED|VERIFY_FAILED/
  // rollback regex does NOT match it (a rejected field had nothing to roll back).
  FIELD_NOT_ALLOWED: 'FIELD_NOT_ALLOWED',

  // ── *_NOT_PERSISTED post-write-verification tokens (DP-16) ──
  WRITE_NOT_PERSISTED: 'WRITE_NOT_PERSISTED',
  ADD_ACTIVE_EFFECT_NOT_PERSISTED: 'ADD_ACTIVE_EFFECT_NOT_PERSISTED',
  UPDATE_ACTIVE_EFFECT_NOT_PERSISTED: 'UPDATE_ACTIVE_EFFECT_NOT_PERSISTED',
  DELETE_ACTIVE_EFFECT_NOT_PERSISTED: 'DELETE_ACTIVE_EFFECT_NOT_PERSISTED',
  APPLY_NPC_CAREER_ADVANCE_NOT_PERSISTED: 'APPLY_NPC_CAREER_ADVANCE_NOT_PERSISTED',
  ARMOURY_REPAIR_NOT_PERSISTED: 'ARMOURY_REPAIR_NOT_PERSISTED',
  BEHAVIOR_WRITE_NOT_PERSISTED: 'BEHAVIOR_WRITE_NOT_PERSISTED',
  CARD_WRITE_NOT_PERSISTED: 'CARD_WRITE_NOT_PERSISTED',
  CARDS_WRITE_NOT_PERSISTED: 'CARDS_WRITE_NOT_PERSISTED',
  CHATMESSAGE_CLEAR_NOT_PERSISTED: 'CHATMESSAGE_CLEAR_NOT_PERSISTED',
  CHATMESSAGE_WRITE_NOT_PERSISTED: 'CHATMESSAGE_WRITE_NOT_PERSISTED',
  COMBATANT_CLEAR_INITIATIVE_NOT_PERSISTED: 'COMBATANT_CLEAR_INITIATIVE_NOT_PERSISTED',
  COMBATANT_REROLL_INITIATIVE_NOT_PERSISTED: 'COMBATANT_REROLL_INITIATIVE_NOT_PERSISTED',
  COMBATANT_SET_DEFEATED_NOT_PERSISTED: 'COMBATANT_SET_DEFEATED_NOT_PERSISTED',
  COMBATANT_SET_HIDDEN_NOT_PERSISTED: 'COMBATANT_SET_HIDDEN_NOT_PERSISTED',
  COMBATANT_SET_INITIATIVE_NOT_PERSISTED: 'COMBATANT_SET_INITIATIVE_NOT_PERSISTED',
  COMBATANT_UPDATE_NOT_PERSISTED: 'COMBATANT_UPDATE_NOT_PERSISTED',
  COMPENDIUM_FOLDER_WRITE_NOT_PERSISTED: 'COMPENDIUM_FOLDER_WRITE_NOT_PERSISTED',
  CREATE_ACTOR_NOT_PERSISTED: 'CREATE_ACTOR_NOT_PERSISTED',
  CSS_WRITE_NOT_PERSISTED: 'CSS_WRITE_NOT_PERSISTED',
  DELETE_ACTOR_NOT_PERSISTED: 'DELETE_ACTOR_NOT_PERSISTED',
  DISEASE_CURE_NOT_PERSISTED: 'DISEASE_CURE_NOT_PERSISTED',
  DISEASE_DECREMENT_NOT_PERSISTED: 'DISEASE_DECREMENT_NOT_PERSISTED',
  DISEASE_FINISH_NOT_PERSISTED: 'DISEASE_FINISH_NOT_PERSISTED',
  DISEASE_INCREMENT_NOT_PERSISTED: 'DISEASE_INCREMENT_NOT_PERSISTED',
  DISEASE_SYMPTOM_NOT_PERSISTED: 'DISEASE_SYMPTOM_NOT_PERSISTED',
  DISEASE_WRITE_NOT_PERSISTED: 'DISEASE_WRITE_NOT_PERSISTED',
  DOCUMENT_IO_WRITE_NOT_PERSISTED: 'DOCUMENT_IO_WRITE_NOT_PERSISTED',
  FILEPICKER_CREATE_DIRECTORY_NOT_PERSISTED: 'FILEPICKER_CREATE_DIRECTORY_NOT_PERSISTED',
  FOLDER_WRITE_NOT_PERSISTED: 'FOLDER_WRITE_NOT_PERSISTED',
  GATHERER_HARVEST_SOURCE_NOT_PERSISTED: 'GATHERER_HARVEST_SOURCE_NOT_PERSISTED',
  GATHERER_RESET_NOT_PERSISTED: 'GATHERER_RESET_NOT_PERSISTED',
  GATHERER_SPOT_FLAG_NOT_PERSISTED: 'GATHERER_SPOT_FLAG_NOT_PERSISTED',
  GMTOOLKIT_SCENE_LIGHT_NOT_PERSISTED: 'GMTOOLKIT_SCENE_LIGHT_NOT_PERSISTED',
  GMTOOLKIT_STATUS_NOT_PERSISTED: 'GMTOOLKIT_STATUS_NOT_PERSISTED',
  GMTOOLKIT_XP_NOT_PERSISTED: 'GMTOOLKIT_XP_NOT_PERSISTED',
  IMPERIAL_ARCANA_RECORD_NOT_PERSISTED: 'IMPERIAL_ARCANA_RECORD_NOT_PERSISTED',
  JOURNAL_WRITE_NOT_PERSISTED: 'JOURNAL_WRITE_NOT_PERSISTED',
  KEYBINDING_NOT_PERSISTED: 'KEYBINDING_NOT_PERSISTED',
  MACRO_IMPORT_NOT_PERSISTED: 'MACRO_IMPORT_NOT_PERSISTED',
  MACRO_SET_TARGET_NOT_PERSISTED: 'MACRO_SET_TARGET_NOT_PERSISTED',
  MASTERCRAFTED_CONSUME_NOT_PERSISTED: 'MASTERCRAFTED_CONSUME_NOT_PERSISTED',
  MASTERCRAFTED_OWNERSHIP_NOT_PERSISTED: 'MASTERCRAFTED_OWNERSHIP_NOT_PERSISTED',
  MASTERCRAFTED_PENDING_CRAFT_NOT_PERSISTED: 'MASTERCRAFTED_PENDING_CRAFT_NOT_PERSISTED',
  MASTERCRAFTED_PRODUCT_NOT_PERSISTED: 'MASTERCRAFTED_PRODUCT_NOT_PERSISTED',
  MATT_ACTIONS_NOT_PERSISTED: 'MATT_ACTIONS_NOT_PERSISTED',
  MATT_CONFIG_NOT_PERSISTED: 'MATT_CONFIG_NOT_PERSISTED',
  MATT_REGION_LINK_NOT_PERSISTED: 'MATT_REGION_LINK_NOT_PERSISTED',
  MATT_TILE_NOT_PERSISTED: 'MATT_TILE_NOT_PERSISTED',
  MATT_VARIABLE_NOT_PERSISTED: 'MATT_VARIABLE_NOT_PERSISTED',
  MODIFY_ITEM_QUALITIES_NOT_PERSISTED: 'MODIFY_ITEM_QUALITIES_NOT_PERSISTED',
  NOTE_WRITE_NOT_PERSISTED: 'NOTE_WRITE_NOT_PERSISTED',
  OWNERSHIP_WRITE_NOT_PERSISTED: 'OWNERSHIP_WRITE_NOT_PERSISTED',
  PARTY_RESOURCES_CREATE_NOT_PERSISTED: 'PARTY_RESOURCES_CREATE_NOT_PERSISTED',
  PARTY_RESOURCES_DELETE_NOT_PERSISTED: 'PARTY_RESOURCES_DELETE_NOT_PERSISTED',
  PATROL_DRAWING_LABEL_NOT_PERSISTED: 'PATROL_DRAWING_LABEL_NOT_PERSISTED',
  PATROL_FLAG_NOT_PERSISTED: 'PATROL_FLAG_NOT_PERSISTED',
  PLAYLIST_BULK_IMPORT_NOT_PERSISTED: 'PLAYLIST_BULK_IMPORT_NOT_PERSISTED',
  PLAYLIST_WRITE_NOT_PERSISTED: 'PLAYLIST_WRITE_NOT_PERSISTED',
  REGION_ADD_SHAPE_NOT_PERSISTED: 'REGION_ADD_SHAPE_NOT_PERSISTED',
  REGION_WRITE_NOT_PERSISTED: 'REGION_WRITE_NOT_PERSISTED',
  ROLLTABLE_WRITE_NOT_PERSISTED: 'ROLLTABLE_WRITE_NOT_PERSISTED',
  SCENE_CLEAR_LAYER_NOT_PERSISTED: 'SCENE_CLEAR_LAYER_NOT_PERSISTED',
  SCENE_IMPORT_NOT_PERSISTED: 'SCENE_IMPORT_NOT_PERSISTED',
  SCENE_LIGHTING_NOT_PERSISTED: 'SCENE_LIGHTING_NOT_PERSISTED',
  SCENE_WRITE_NOT_PERSISTED: 'SCENE_WRITE_NOT_PERSISTED',
  SET_ART_NOT_PERSISTED: 'SET_ART_NOT_PERSISTED',
  SETTING_WRITE_NOT_PERSISTED: 'SETTING_WRITE_NOT_PERSISTED',
  TILE_ZORDER_NOT_PERSISTED: 'TILE_ZORDER_NOT_PERSISTED',
  TIMEKEEPING_EVENT_FLAG_NOT_PERSISTED: 'TIMEKEEPING_EVENT_FLAG_NOT_PERSISTED',
  TIMEKEEPING_SYNC_NOT_PERSISTED: 'TIMEKEEPING_SYNC_NOT_PERSISTED',
  TOKEN_WRITE_NOT_PERSISTED: 'TOKEN_WRITE_NOT_PERSISTED',
  TRADE_ITEM_SOURCE_DECREMENT_NOT_PERSISTED: 'TRADE_ITEM_SOURCE_DECREMENT_NOT_PERSISTED',
  UPDATE_ACTOR_NOT_PERSISTED: 'UPDATE_ACTOR_NOT_PERSISTED',
  UPDATE_ITEM_NOT_PERSISTED: 'UPDATE_ITEM_NOT_PERSISTED',
  UPDATE_PROTOTYPE_TOKEN_NOT_PERSISTED: 'UPDATE_PROTOTYPE_TOKEN_NOT_PERSISTED',
  UPDATE_STATS_NOT_PERSISTED: 'UPDATE_STATS_NOT_PERSISTED',
  USER_WRITE_NOT_PERSISTED: 'USER_WRITE_NOT_PERSISTED',
  XP_TOTAL_NOT_PERSISTED: 'XP_TOTAL_NOT_PERSISTED',
} as const;

export type ErrorToken = (typeof ErrorTokens)[keyof typeof ErrorTokens];

const ERROR_TOKEN_VALUES = new Set<string>(Object.values(ErrorTokens));

/** True if `s` is exactly one of the registered error-token values. */
export function isErrorToken(s: string): s is ErrorToken {
  return ERROR_TOKEN_VALUES.has(s);
}
