name: Build & Release Foundry Module
on:
  workflow_dispatch:
  push:
    tags: [ "foundry-module-v*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Create module zip
        run: |
          cd packages/foundry-module
          zip -r ../../foundry-vtt-mcp.zip . -x ".*" -x "node_modules/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: foundry-vtt-mcp.zip
          generate_release_notes: true